version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
build_script:
- pwsh: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Apps.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: yHXRu2WkW8o4sFeY4T5bAclZ58y46Nqsqq1eaTTkm0bA5iU2JnAndsLtKIhk9/qb
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Seq.Api.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
